# Generated by Django 4.2.4 on 2023-08-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_album_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers'),
        ),
    ]
