# Generated by Django 4.2.4 on 2023-08-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_album_album_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_cover',
        ),
    ]
